"""Add preview_picture_path to courses and create course_documents table

Revision ID: 19345ac1a813
Revises: audit_system_001
Create Date: 2025-08-28 02:38:26.110800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19345ac1a813'
down_revision: Union[str, Sequence[str], None] = 'audit_system_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('document_path', sa.String(length=500), nullable=True, comment='Path to document file'),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True, comment='File type: PDF, DOCX, etc.'),
    sa.Column('document_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_documents_id'), 'course_documents', ['id'], unique=False)
    op.alter_column('attendance_cards', 'card_uid',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique ID from the card (RFID/NFC UID, Barcode)',
               existing_nullable=False)
    op.drop_index(op.f('ix_attendance_records_student_swiped'), table_name='attendance_records')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_path'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_response_status_code'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_card_assignments_card_revoked'), table_name='card_assignments')
    op.drop_index(op.f('ix_card_assignments_student_revoked'), table_name='card_assignments')
    op.add_column('courses', sa.Column('preview_picture_path', sa.String(length=500), nullable=True, comment='Path to course preview picture for lazy loading'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'preview_picture_path')
    op.create_index(op.f('ix_card_assignments_student_revoked'), 'card_assignments', ['student_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_card_assignments_card_revoked'), 'card_assignments', ['card_uid', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_response_status_code'), 'audit_logs', ['response_status_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_path'), 'audit_logs', ['request_path'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_swiped'), 'attendance_records', ['student_id', 'swiped_at'], unique=False)
    op.alter_column('attendance_cards', 'card_uid',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique ID from the card (RFID/NFC UID, Barcode)',
               existing_nullable=False)
    op.drop_index(op.f('ix_course_documents_id'), table_name='course_documents')
    op.drop_table('course_documents')
    # ### end Alembic commands ###
