"""Description of changes

Revision ID: 243968e3407e
Revises: 8da7711e9811
Create Date: 2025-07-10 15:54:09.381990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '243968e3407e'
down_revision: Union[str, Sequence[str], None] = '8da7711e9811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_edit_permissions',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'instructor_id')
    )
    op.create_table('course_payment_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_payment_period_id'), 'course_payment_period', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('payment_period_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['payment_period_id'], ['course_payment_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'payment_period_id', name='unique_enrollment_payment_period')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.add_column('courses', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('start_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('teacher_name', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('invoice_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('payments_course_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('payments', 'user_id')
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Denormalized for easy lookup'))
    op.add_column('payments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('payments_course_id_fkey'), 'payments', 'courses', ['course_id'], ['id'])
    op.drop_column('payments', 'invoice_id')
    op.drop_column('courses', 'teacher_name')
    op.drop_column('courses', 'start_data')
    op.drop_column('courses', 'location')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_course_payment_period_id'), table_name='course_payment_period')
    op.drop_table('course_payment_period')
    op.drop_table('course_edit_permissions')
    # ### end Alembic commands ###
