"""description

Revision ID: 59541f301e98
Revises: 675d2f5e7540
Create Date: 2025-07-02 08:02:58.566573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59541f301e98'
down_revision: Union[str, Sequence[str], None] = '675d2f5e7540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.drop_column('user_profiles', 'bio')
    op.drop_column('user_profiles', 'avatar_url')
    op.drop_column('user_profiles', 'timezone')
    op.drop_column('user_profiles', 'github_url')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'language')
    op.drop_column('user_profiles', 'headline')
    op.drop_column('user_profiles', 'website_url')
    op.drop_column('user_profiles', 'display_name')
    op.drop_column('user_profiles', 'updated_at')
    op.drop_column('user_profiles', 'twitter_handle')
    op.drop_column('user_profiles', 'linkedin_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('twitter_handle', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Store just the handle, not the full URL'))
    op.add_column('user_profiles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Publicly visible name. Can default to first_name + last_name'))
    op.add_column('user_profiles', sa.Column('website_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('headline', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='A short, one-line bio. e.g., "Full-Stack Developer | Lifelong Learner"'))
    op.add_column('user_profiles', sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Preferred language for the UI (e.g., en-US, es-ES)'))
    op.add_column('user_profiles', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='e.g., "San Francisco, CA"'))
    op.add_column('user_profiles', sa.Column('github_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Important for displaying deadlines correctly (e.g., "America/New_York")'))
    op.add_column('user_profiles', sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='URL to the user profile image'))
    op.add_column('user_profiles', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'avatar')
    # ### end Alembic commands ###
