"""update card model

Revision ID: 61e1c86a9fec
Revises: ae55f30c532f
Create Date: 2025-10-29 06:12:15.968779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e1c86a9fec'
down_revision: Union[str, Sequence[str], None] = 'ae55f30c532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_cards', sa.Column('card_uuid', sa.UUID(), nullable=True, comment='Optional NFC UUID; may be NULL while systems are not synced'))
    op.add_column('attendance_cards', sa.Column('branch_id', sa.UUID(), nullable=False, comment='Branch this card belongs to - determines building access'))
    op.create_foreign_key(None, 'attendance_cards', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_cards', type_='foreignkey')
    op.drop_column('attendance_cards', 'branch_id')
    op.drop_column('attendance_cards', 'card_uuid')
    # ### end Alembic commands ###
