"""Description of changes

Revision ID: 8da7711e9811
Revises: 59541f301e98
Create Date: 2025-07-05 18:12:21.047354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8da7711e9811'
down_revision: Union[str, Sequence[str], None] = '59541f301e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the foreign key constraint and column from payments
    op.drop_constraint('payments_subscription_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'subscription_id')
    
    # Then drop the subscriptions table
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    
    # Drop student activity log
    op.drop_index(op.f('ix_student_activity_log_id'), table_name='student_activity_log')
    op.drop_table('student_activity_log')
    
    # Drop course columns
    op.drop_column('courses', 'payment_type')
    op.drop_column('courses', 'billing_interval_count')
    op.drop_column('courses', 'billing_interval')
    op.drop_column('courses', 'subscription_price')
    op.drop_column('courses', 'is_usage_based')
    
    # Add updated_at column to payments
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # Alter users table
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('payments', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='NULL for one-time payments'))
    op.create_foreign_key(op.f('payments_subscription_id_fkey'), 'payments', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_column('payments', 'updated_at')
    op.add_column('courses', sa.Column('is_usage_based', sa.BOOLEAN(), autoincrement=False, nullable=True, comment="Set to true for 'learning days' model"))
    op.add_column('courses', sa.Column('subscription_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Price per billing interval'))
    op.add_column('courses', sa.Column('billing_interval', sa.INTEGER(), autoincrement=False, nullable=True, comment='e.g., MONTH, DAY'))
    op.add_column('courses', sa.Column('billing_interval_count', sa.INTEGER(), autoincrement=False, nullable=True, comment="e.g., for 'every 10 days', interval is DAY and count is 10"))
    op.add_column('courses', sa.Column('payment_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('student_activity_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('student_activity_log_course_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('student_activity_log_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_activity_log_pkey')),
    sa.UniqueConstraint('student_id', 'course_id', 'activity_date', name=op.f('unique_student_course_activity'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_student_activity_log_id'), 'student_activity_log', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_period_starts_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_period_ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='For time-based, this is calculated. For usage-based, this is updated when a cycle ends.'),
    sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('subscriptions_enrollment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey')),
    sa.UniqueConstraint('enrollment_id', name=op.f('subscriptions_enrollment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###
