"""add phone number to user

Revision ID: ae55f30c532f
Revises: 5d7610e19e91
Create Date: 2025-10-27 07:34:23.284608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae55f30c532f'
down_revision: Union[str, Sequence[str], None] = '5d7610e19e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('phone_number', sa.String(length=20), nullable=True, comment='Số điện thoại của người dùng'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'phone_number')
    # ### end Alembic commands ###
