"""fix typo on course table

Revision ID: c1b178ca1950
Revises: 243968e3407e
Create Date: 2025-07-10 16:04:13.177436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1b178ca1950'
down_revision: Union[str, Sequence[str], None] = '243968e3407e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('courses', 'start_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('start_data', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('courses', 'start_date')
    # ### end Alembic commands ###
