"""Add branch_id to courses table

Revision ID: cb41d73c0458
Revises: dee51457859e
Create Date: 2025-10-23 14:57:14.343114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb41d73c0458'
down_revision: Union[str, Sequence[str], None] = 'dee51457859e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_cards', 'card_uid',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique ID from the card (RFID/NFC UID, Barcode). This is the physical identifier.',
               existing_nullable=False)
    op.alter_column('attendance_records', 'card_uid_used',
               existing_type=sa.VARCHAR(length=255),
               comment='Which card UID was used for this specific swipe',
               existing_nullable=False)
    op.alter_column('branches', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Tên cơ sở, ví dụ: "Cơ sở Cầu Giấy"',
               existing_nullable=False)
    op.alter_column('card_assignments', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL if currently active.',
               existing_nullable=True)
    op.alter_column('course_documents', 'document_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Path to document file',
               existing_nullable=True)
    op.alter_column('course_documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               comment='File type: PDF, DOCX, etc.',
               existing_nullable=True)
    op.alter_column('course_documents', 'document_size',
               existing_type=sa.INTEGER(),
               comment='File size in bytes',
               existing_nullable=True)
    op.drop_index(op.f('ix_course_documents_course_active'), table_name='course_documents')
    op.create_index(op.f('ix_course_documents_course_id'), 'course_documents', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_documents_is_active'), 'course_documents', ['is_active'], unique=False)
    op.alter_column('course_schedules', 'start_time',
               existing_type=postgresql.TIME(),
               comment='e.g., 17:00:00',
               existing_nullable=False)
    op.alter_column('course_schedules', 'end_time',
               existing_type=postgresql.TIME(),
               comment='e.g., 18:30:00',
               existing_nullable=False)
    op.add_column('courses', sa.Column('branch_id', sa.UUID(), nullable=True, comment='Chi nhánh nơi tổ chức khóa học'))
    op.alter_column('courses', 'group_chat_link',
               existing_type=sa.VARCHAR(length=500),
               comment='Link nhóm Zalo, Facebook, etc. của lớp học',
               existing_nullable=True)
    op.create_foreign_key(None, 'courses', 'branches', ['branch_id'], ['id'])
    op.alter_column('enrollments', 'discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Tỉ lệ miễn giảm học phí áp dụng cho lần đăng ký này',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('enrollments', 'discount_reason',
               existing_type=sa.TEXT(),
               comment='Lý do miễn giảm',
               existing_nullable=True)
    op.alter_column('enrollments', 'discount_approved_by',
               existing_type=sa.UUID(),
               comment='ID của người duyệt miễn giảm',
               existing_nullable=True)
    op.alter_column('guardians', 'notes',
               existing_type=sa.TEXT(),
               comment='Ghi chú cho team sale: công việc, sở thích, thói quen của phụ huynh...',
               existing_nullable=True)
    op.alter_column('invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Số tiền phải trả SAU KHI đã áp dụng miễn giảm',
               existing_nullable=False)
    op.alter_column('payments', 'provider_reference',
               existing_type=sa.VARCHAR(length=255),
               comment='ID from Stripe, PayPal, etc.',
               existing_nullable=True)
    op.alter_column('rooms', 'room_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Số phòng hoặc tên phòng, ví dụ: "P101"',
               existing_nullable=False)
    op.alter_column('student_guardian_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=50),
               comment='e.g., "Father", "Mother", "Guardian"',
               existing_nullable=True)
    op.alter_column('user_profiles', 'current_school',
               existing_type=sa.VARCHAR(length=255),
               comment='Trường học sinh đang theo học',
               existing_nullable=True)
    op.alter_column('user_profiles', 'current_grade',
               existing_type=sa.VARCHAR(length=50),
               comment='Lớp chính khóa của học sinh (vd: 10A1)',
               existing_nullable=True)
    op.alter_column('user_profiles', 'default_discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Mức giảm giá mặc định từ trung tâm cho học sinh này',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'default_discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Mức giảm giá mặc định từ trung tâm cho học sinh này',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('user_profiles', 'current_grade',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Lớp chính khóa của học sinh (vd: 10A1)',
               existing_nullable=True)
    op.alter_column('user_profiles', 'current_school',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Trường học sinh đang theo học',
               existing_nullable=True)
    op.alter_column('student_guardian_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='e.g., "Father", "Mother", "Guardian"',
               existing_nullable=True)
    op.alter_column('rooms', 'room_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Số phòng hoặc tên phòng, ví dụ: "P101"',
               existing_nullable=False)
    op.alter_column('payments', 'provider_reference',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID from Stripe, PayPal, etc.',
               existing_nullable=True)
    op.alter_column('invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Số tiền phải trả SAU KHI đã áp dụng miễn giảm',
               existing_nullable=False)
    op.alter_column('guardians', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ghi chú cho team sale: công việc, sở thích, thói quen của phụ huynh...',
               existing_nullable=True)
    op.alter_column('enrollments', 'discount_approved_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID của người duyệt miễn giảm',
               existing_nullable=True)
    op.alter_column('enrollments', 'discount_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Lý do miễn giảm',
               existing_nullable=True)
    op.alter_column('enrollments', 'discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Tỉ lệ miễn giảm học phí áp dụng cho lần đăng ký này',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.alter_column('courses', 'group_chat_link',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Link nhóm Zalo, Facebook, etc. của lớp học',
               existing_nullable=True)
    op.drop_column('courses', 'branch_id')
    op.alter_column('course_schedules', 'end_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='e.g., 18:30:00',
               existing_nullable=False)
    op.alter_column('course_schedules', 'start_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='e.g., 17:00:00',
               existing_nullable=False)
    op.drop_index(op.f('ix_course_documents_is_active'), table_name='course_documents')
    op.drop_index(op.f('ix_course_documents_course_id'), table_name='course_documents')
    op.create_index(op.f('ix_course_documents_course_active'), 'course_documents', ['course_id', 'is_active'], unique=False)
    op.alter_column('course_documents', 'document_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='File size in bytes',
               existing_nullable=True)
    op.alter_column('course_documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='File type: PDF, DOCX, etc.',
               existing_nullable=True)
    op.alter_column('course_documents', 'document_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Path to document file',
               existing_nullable=True)
    op.alter_column('card_assignments', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='NULL if currently active.',
               existing_nullable=True)
    op.alter_column('branches', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Tên cơ sở, ví dụ: "Cơ sở Cầu Giấy"',
               existing_nullable=False)
    op.alter_column('attendance_records', 'card_uid_used',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Which card UID was used for this specific swipe',
               existing_nullable=False)
    op.alter_column('attendance_cards', 'card_uid',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique ID from the card (RFID/NFC UID, Barcode). This is the physical identifier.',
               existing_nullable=False)
    # ### end Alembic commands ###
